### ISSUE TITLE
Why use double node_modules?

### ISSUE THREAD

**Issue by Zyles** [quasarframework/electron-wrapper#11]
My app directory grew by 210 MB because you are using a second node_modules for /electron instead of utilizing the one in the main project.

Can this not be more efficient to merge it? I don't understand the need for separation here.

Here is a way to solve it: https://github.com/SimulatedGREG/electron-vue/

Also has better colored console which is helpful.

**Comment by rstoenescu** [comment]
@Zyles hi,

An Electron app has two processes running: the main thread and the renderer thread. Main thread is your /electron folder generated by the Electron wrapper, and the renderer thread is the actual Quasar app. Each have its own needs so that's why two node_modules folders.

Furthermore the point is to be able to write website + mobile apps + electron apps using the same project folder. Consider the Electron (or Cordova for that matter) wrapper as an addon to the default project folder being generated by the Quasar CLI.

There is a starter kit on the roadmap specifically for building ONLY Electron apps, which will be highly optimized to do just that.

PS: please use [forum](http://forum.quasar-framework.org/) for questions. Thanks.

Regards,
Razvan
